def input_data():
    # Opens the file 'input_data' in write mode ('w')
    with open('input_data', 'w') as file:
        # Writes the data to the file
        file.write('RUNNR	1						run number\n')
        file.write('NSHOW	1						number of showers to generate\n')
        file.write('PRMPAR	1						prim. particle (1=gamma, 14=proton, ...)\n')
        file.write('ESLOPE	-2.7						slope of primary energy spectrum\n')
        file.write('ERANGE	1.E3	1.E3					energy range of primary particle (GeV)\n')
        file.write('THETAP	0.	0.					range of zenith angle (degree)\n')
        file.write('PHIP	-180.	180.					range of azimuth angle (degree)\n')
        file.write('SEED	1	0	0				seed for 1. random number sequence\n')
        file.write('SEED	2	0	0				seed for 2. random number sequence\n')
        file.write('*THIN	1.E-2	1.E-2	0.				thinning definition\n')
        file.write('*THINH	10.	10.					relative threshold and weight for hadron thinning\n')
        file.write('OBSLEV	0.						observation level (in cm)\n')
        file.write('MAGNET	20.0	42.8					magnetic field centr. Europe\n')
        file.write('HADFLG	0	0	0	0	0	2	flags hadr.interact.&fragmentation\n')
        file.write('ECUTS	1.	1.	0.001	0.001			energy cuts for particles\n')
        file.write('MUADDI	T						additional info for muons\n')
        file.write('MUMULT	T						muon multiple scattering angle\n')
        file.write('PLOTSH	T									\n')
        file.write('ELMFLG	T	T					em. interaction flags (NKG,EGS)\n')
        file.write('STEPFC	1.0						mult. scattering step length fact.\n')
        file.write('RADNKG	200.E2						outer radius for NKG lat.dens.distr.\n')
        file.write('EPOPAR	input	../epos/epos.param			!initialization input file for epos\n')
        file.write('EPOPAR	fname	inics	../epos/epos.inics		!initialization input file for epos\n')
        file.write('EPOPAR	fname	iniev	../epos/epos.iniev		!initialization input file for epos\n')
        file.write('EPOPAR	fname	initl	../epos/epos.initl		!initialization input file for epos\n')
        file.write('EPOPAR	fname	inirj	../epos/epos.inirj		!initialization input file for epos\n')
        file.write('EPOPAR	fname	inihy	../epos/epos.ini1b		!initialization input file for epos\n')
        file.write('EPOPAR	fname	check	none				!dummy output file for epos\n')
        file.write('EPOPAR	fname	histo	none				!dummy output file for epos\n')
        file.write('EPOPAR	fname	data	none				!dummy output file for epos\n')
        file.write('EPOPAR	fname	copy	none				!dummy output file for epos\n')                                        
        file.write('LONGI	T	10.	F	F			longit.distr. & step size & fit & outfile\n')
        file.write('ECTMAP	1.E11						cut on gamma factor for printout\n')
        file.write('MAXPRT	1						max. number of printed events\n')
        file.write('DIRECT	./						output directory\n')
        file.write('USER	you						user\n')
        file.write('*PAROUT	F	F					supress DAT file\n')
        file.write('DEBUG	F	6	F	1000000			debug flag and log.unit for out\n')
        file.write('EXIT							terminates input')
